# Generated by Django 5.0.6 on 2024-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsform',
            name='date',
        ),
        migrations.AddField(
            model_name='contactsform',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
