# Generated by Django 5.0.7 on 2024-08-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
    ]
