# Generated by Django 5.0.7 on 2024-09-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_commentreply'),
        ('core', '0009_subscriber'),
    ]

    operations = [
    ]
