# Generated by Django 5.0.7 on 2024-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_roadmapimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
