# Generated by Django 5.0.7 on 2024-08-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="categories",
            new_name="category",
        ),
    ]
