# Generated by Django 5.0.7 on 2024-09-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectshowcase", "0002_projectshowcaseimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectshowcase",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name of project"),
        ),
    ]
